data:
  augmented_dataset_path: data/processed/imdb_augmented
  cache_dir: ./data/processed
  dataset_name: imdb
  max_length: 128
  train_split: train
  use_augmented_dataset: false
  validation_split: test
model:
  name: distilbert-base-uncased
  save_dir: models/sentiment_improved
testing:
  confidence_threshold: 0.7
  evaluation_metrics:
  - accuracy
  - f1
  performance_test:
    batch_size: 32
    latency_threshold_ms: 100
  test_batch_size: 16
  test_examples_file: data/processed/sentiment_test_examples.json
training:
  batch_size: 16
  eval_steps: 500
  evaluation_strategy: steps
  fp16: true
  gradient_accumulation_steps: 2
  learning_rate: 2.0e-05
  logging_dir: ./logs/sentiment
  num_train_epochs: 3.0
  save_steps: 1000
  save_total_limit: 2
  warmup_steps: 500
  weight_decay: 0.01
