name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Download pre-trained model
      run: |
        mkdir -p models/sentiment
        # Use huggingface_hub to download a pre-trained model
        # This is a placeholder - replace with your actual model or a public model
        python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='distilbert-base-uncased-finetuned-sst-2-english', local_dir='models/sentiment')"
        
    - name: Run unit tests
      run: |
        pytest tests/test_sentiment_model.py -v
        
    - name: Generate coverage report
      run: |
        pytest --cov=src --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: false
        
    - name: Run challenge tests
      run: |
        # Create necessary directories
        mkdir -p reports
        # Run challenge tests with the downloaded model
        python -m src.model.sentiment_challenge_test --model_dir models/sentiment
        
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/ 